import type { Metadata } from "next";
import { AuthProvider } from "@/components/AuthProvider";
import GlobalBottomTabs from "@/components/GlobalBottomTabs";
import "./globals.css";
import localFont from "next/font/local";

const montserrat = localFont({
  src: [
    {
      path: "../public/fonts/Montserrat-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Montserrat-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Montserrat-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
  icon: "/icon-512.png",
  apple: "/icon-512.png",
},
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
  <html lang="de">
    <head>
      <meta name="apple-mobile-web-app-capable" content="yes" />
      <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      <meta name="apple-mobile-web-app-title" content="JuniorsTaste" />
      <meta name="theme-color" content="#0f3b2e" />
      <link rel="apple-touch-icon" href="/icon-512.png" />
      <link rel="preconnect" href="https://www.tiktok.com" />
      <link rel="preconnect" href="https://www.tiktokcdn.com" />
      <link rel="preconnect" href="https://lf16-tiktok-web.tiktokcdn-us.com" />
      <link rel="dns-prefetch" href="https://www.tiktok.com" />
      <link rel="dns-prefetch" href="https://www.tiktokcdn.com" />
      <link rel="dns-prefetch" href="https://lf16-tiktok-web.tiktokcdn-us.com" />
    </head>
    <body className={montserrat.className}>
      <AuthProvider>
        {children}
        <GlobalBottomTabs />
      </AuthProvider>
    </body>
  </html>
);
}
