import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["600", "700", "800"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
  icon: "/icon-512.png",
  apple: "/icon-512.png",
},
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
  <html lang="de">
    <head>
      <meta name="apple-mobile-web-app-capable" content="yes" />
      <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      <meta name="apple-mobile-web-app-title" content="JuniorsTaste" />
      <meta name="theme-color" content="#0f3b2e" />
      <link rel="apple-touch-icon" href="/icon-512.png" />
    </head>
    <body className={montserrat.className}>{children}</body>
  </html>
);
}
